Today we had a session that we wrote code in, we have learned how to use the numpy library. Where we have perfomred many operations including finding the tf idf of the docummets.

Use the numby to covery to array

In [ ]:
import numpy as np
listx = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
np.array(listx)
arrx= np.array(listx)
arrx.mean(axis=1)

Used the np to find the tf dif

In [2]:
import numpy as np

# create documents
docs = [
    "this is first doc",
    "this doc is 2nd",
    "in the doc no. 3"
]

# initialize using zeros 
tf = np.zeros([3, 8])

# use the zeros to initialize them all to 0 and there is also the ones method
tf = np.zeros([len(docs), 8])
print(tf)

terms = []

for doc in docs:
    terms += doc.split()

# find the unique terms by using the set 
unique_terms = set(terms)
print(unique_terms)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
{'no.', 'is', 'this', '2nd', 'doc', '3', 'first', 'in', 'the'}
